const OFF = 0;

module.exports = {
  rules: {
    'for-direction': OFF,
    'getter-return': OFF,
    'no-async-promise-executor': OFF,
    'no-await-in-loop': OFF,
    'no-compare-neg-zero': OFF,
    'no-cond-assign': OFF,
    'no-console': OFF,
    'no-constant-condition': OFF,
    'no-control-regex': OFF,
    'no-debugger': OFF,
    'no-dupe-args': OFF,
    'no-dupe-keys': OFF,
    'no-duplicate-case': OFF,
    'no-empty': OFF,
    'no-empty-character-class': OFF,
    'no-ex-assign': OFF,
    'no-extra-boolean-cast': OFF,
    'no-extra-parens': OFF,
    'no-extra-semi': OFF,
    'no-func-assign': OFF,
    'no-inner-declarations': OFF,
    'no-invalid-regexp': OFF,
    'no-irregular-whitespace': OFF,
    'no-misleading-character-class': OFF,
    'no-obj-calls': OFF,
    'no-prototype-builtins': OFF,
    'no-regex-spaces': OFF,
    'no-sparse-arrays': OFF,
    'no-template-curly-in-string': OFF,
    'no-unexpected-multiline': OFF,
    'no-unreachable': OFF,
    'no-unsafe-finally': OFF,
    'no-unsafe-negation': OFF,
    'require-atomic-updates': OFF,
    'use-isnan': OFF,
    'valid-jsdoc': OFF,
    'valid-typeof': OFF,
  },
};
