const OFF = 0;

module.exports = {
  rules: {
    'jsx-a11y/accessible-emoji': OFF,
    'jsx-a11y/alt-text': OFF,
    'jsx-a11y/aria-activedescendant-has-tabindex': OFF,
    'jsx-a11y/anchor-has-content': OFF,
    'jsx-a11y/anchor-is-valid': OFF,
    'jsx-a11y/aria-props': OFF,
    'jsx-a11y/aria-proptypes': OFF,
    'jsx-a11y/aria-role': OFF,
    'jsx-a11y/aria-unsupported-elements': OFF,
    'jsx-a11y/click-events-have-key-events': OFF,
    'jsx-a11y/heading-has-content': OFF,
    'jsx-a11y/html-has-lang': OFF,
    'jsx-a11y/iframe-has-title': OFF,
    'jsx-a11y/img-redundant-alt': OFF,
    'jsx-a11y/interactive-supports-focus': OFF,
    'jsx-a11y/lang': OFF,
    'jsx-a11y/media-has-caption': OFF,
    'jsx-a11y/mouse-events-have-key-events': OFF,
    'jsx-a11y/no-access-key': OFF,
    'jsx-a11y/no-autofocus': OFF,
    'jsx-a11y/no-distracting-elements': OFF,
    'jsx-a11y/no-interactive-element-to-noninteractive-role': OFF,
    'jsx-a11y/no-noninteractive-element-interactions': OFF,
    'jsx-a11y/no-noninteractive-element-to-interactive-role': OFF,
    'jsx-a11y/no-noninteractive-tabindex': OFF,
    'jsx-a11y/no-onchange': OFF,
    'jsx-a11y/no-redundant-roles': OFF,
    'jsx-a11y/no-static-element-interactions': OFF,
    'jsx-a11y/role-has-required-aria-props': OFF,
    'jsx-a11y/role-supports-aria-props': OFF,
    'jsx-a11y/scope': OFF,
    'jsx-a11y/tabindex-no-positive': OFF,
  }
};
