const OFF = 0;

module.exports = {
  rules: {
    'arrow-body-style': OFF,
    'arrow-parens': OFF,
    'arrow-spacing': OFF,
    'constructor-super': OFF,
    'generator-star-spacing': OFF,
    'no-class-assign': OFF,
    'no-confusing-arrow': OFF,
    'no-const-assign': OFF,
    'no-dupe-class-members': OFF,
    'no-duplicate-imports': OFF,
    'no-new-symbol': OFF,
    'no-restricted-imports': OFF,
    'no-this-before-super': OFF,
    'no-useless-computed-key': OFF,
    'no-useless-constructor': OFF,
    'no-useless-rename': OFF,
    'no-var': OFF,
    'object-shorthand': OFF,
    'prefer-arrow-callback': OFF,
    'prefer-const': OFF,
    'prefer-destructuring': OFF,
    'prefer-numeric-literals': OFF,
    'prefer-rest-params': OFF,
    'prefer-spread': OFF,
    'prefer-template': OFF,
    'require-yield': OFF,
    'rest-spread-spacing': OFF,
    'sort-imports': OFF,
    'symbol-description': OFF,
    'template-curly-spacing': OFF,
    'yield-star-spacing': OFF,
  },
};
